# Generated by Django 2.0.8 on 2018-09-18 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=200)),
                ('empId', models.DecimalField(decimal_places=10, max_digits=19)),
                ('meal_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
