# Generated by Django 2.0.8 on 2018-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='meal_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
