# Generated by Django 2.0.8 on 2018-09-20 08:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='lunch',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='token',
            name='empId',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
