# Generated by Django 2.0.8 on 2018-09-19 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='lunch',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='empId',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
