# Generated by Django 2.0.8 on 2018-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_auto_20180920_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=13),
        ),
    ]
