# Generated by Django 2.0.8 on 2018-09-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_auto_20180920_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='meal_date',
            field=models.DateField(auto_now=True),
        ),
    ]
