# Generated by Django 2.0.8 on 2018-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20180920_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='search_word',
        ),
        migrations.AddField(
            model_name='data',
            name='firstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
