# Generated by Django 2.0.8 on 2018-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_auto_20180920_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
    ]
